### ISSUE TITLE
Source code problem

### ISSUE THREAD

**Issue by upekshapriya** [M2000Interpreter/DVmateEn#3]
The source code appears to be the same file as the main file (although zipped up) and so is an executable and not editable.

It appears from https://sourceforge.net/p/gambas/mailman/message/15238441/ that it's possible to make a source archive with 
Menu Project/Make source archive in the IDE

**Comment by M2000Interpreter** [comment]
There are more files than one. They are hidden because they start with .
I am using Ubuntu Studio, and I just check it is ok.
So first you have to open zip and see that there are some folders there. Copy all in a place and then start Gambas and open a project from disk, just show the place you through files to.

**Comment by upekshapriya** [comment]
Thanks I see now. Maybe you could add some instructions to this effect for other people?
